export const HOMEPAGE = "/";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";  
export const DETAILS="/details/:id";
export const CART="/cart";
export const CHECKOUT="/checkout";
export const FAVORITES="/favorites";
export const COLLECTIONS = "/collections";
export const WINTER = "/winter";
export const SHOPPING = '/shopping';
export const SPRING = '/spring'; 
export const ABOUTUS = '/aboutus'; 
export const SUMMER = '/summer'; 
export const TailorMainPage = "/tailor"
export const BLOGDETAILS = "/post/:id"
export const BLOG = '/blog';
export const ADMIN = '/admin';
export const CREATEPRODUCT= '/admin/products'; 
export const SEARCH= '/search'; 
